filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    
processors:
- grok:
    patterns: ["%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:host} %{DATA:component}(?:\\[%{POSINT:forget}\\])?: %{GREEDYDATA:syslog_message}"]
    timestamps: ["Jan _2 15:04:05"]
- javascript:
    file: "fb.js"
      
output.console:
  enabled: false
  codec.avro:
    file: "fb.json"
output.kafka:
  enabled: true
  # initial brokers for reading cluster metadata
  hosts: ["192.168.0.163:9092"]

  # message topic selection + partitioning
  topic: 'topic_avro_syslog'
  partition.round_robin:
    reachable_only: true
  compression_level: 0
  required_acks: 0
  codec.avro:
    file: "fb.json"
