metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
  processors:
  - javascript:
      file: "mb.js"

logging:
  - level: debug
    to_syslog: false
output.console:
  enabled: false
  pretty: true

output.kafka:
  enabled: true
  hosts: ["192.168.0.163:9092"]
  topic: 'topic_avro_syslog'
  version: 0.9
  compression: none
  compression_level: 0
  keep_alive: 3
  required_acks: 0
  client_id: 'filebeat'
  codec.avro:
    file: "fb.json"
  channel_buffer_size: 1


